---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-owner-listener
spec:
  triggers:
    - name: github-owners-listener
      interceptors:
        - ref:
            name: "github-owners"
          params:
            - name: "secretRef"
              value:
                secretName: github-secret
                secretKey: secretToken
            - name: "orgPublicMemberAllowed"
              value: true
            - name: "repoMemberAllowed"
              value: true
      bindings:
        - ref: github-owners-pr-binding
      template:
        ref: github-owners-template
  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            serviceAccountName: tekton-triggers-example-sa
            containers:
              - resources:
                  requests:
                    memory: "64Mi"
                    cpu: "250m"
                  limits:
                    memory: "128Mi"
                    cpu: "500m"
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-owners-pr-binding
spec:
  params:
    - name: gitrepositoryurl
      value: $(body.repository.clone_url)

---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: github-owners-template
spec:
  params:
    - name: gitrepositoryurl
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: TaskRun
      metadata:
        generateName: github-owners-run-
      spec:
        taskSpec:
          steps:
            - name: example
              image: ubuntu
              script: |
                #! /bin/bash

                echo ""
                echo "RepoURL is $(tt.params.gitrepositoryurl)"